name: Ottimizzazione immagini
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "logos/it/**"
jobs:
  optimize-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installa Bun
        uses: oven-sh/setup-bun@v2

      - name: Genera file ratio
        shell: bash
        working-directory: ./
        run: |
          bun install
          bun generate-logo-ratios.mjs --country it

      - uses: ZapprTV/optimize-images@main
        with:
          libwebp-version: "1.3.2"
          directory: "logos/it"